// Generated by CoffeeScript 1.12.0
(function() {
  var AppViewModel, d;

  d = new Date();

  AppViewModel = function() {
    this.months = ko.observableArray(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'Ocotober', 'November', 'December']);
    this.year = ko.observable(d.getFullYear());
    this.index = ko.observable(d.getMonth());
    this.days = ko.observableArray([]);
    this.date = ko.pureComputed((function() {
      var a;
      a = this.index();
      return this.months()[a] + ' | ' + this.year();
    }), this);
    this.daysOfMonth = ko.computed((function() {
      var a, currentDays, endDay, i, l, month, numberOfDays, postDays, preDays, startDay, year;
      month = this.index();
      year = this.year.peek();
      numberOfDays = new Date(year, month + 1, 0).getDate();
      startDay = new Date(year, month, 1).getDay();
      endDay = new Date(year, month, numberOfDays).getDay();
      a = numberOfDays - startDay;
      while (a < numberOfDays) {
        preDays = {
          date: a,
          pre: true
        };
        this.days.push(preDays);
        a++;
      }
      i = 1;
      while (i < numberOfDays + 1) {
        currentDays = {
          date: i,
          current: true
        };
        this.days.push(currentDays);
        i++;
      }
      l = 1;
      while (l < 7 - endDay) {
        postDays = {
          date: l,
          post: true
        };
        this.days.push(postDays);
        l++;
      }
    }), this);
    this.plusMonth = function() {
      this.days([]);
      if (this.index() < 11) {
        this.index(this.index() + 1);
      } else if (this.index() === 11) {
        this.year(this.year() + 1);
        this.index(0);
      }
    };
    this.minusMonth = function() {
      this.days([]);
      if (this.index() > 0) {
        this.index(this.index() - 1);
      } else if (this.index() === 0) {
        this.year(this.year() - 1);
        this.index(11);
      }
    };
  };

  ko.applyBindings(new AppViewModel);

}).call(this);
